version: '3.8'

services:

  mysql-db:
    image: mysql:8.0
    container_name: task-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: task-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - task-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: task-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - task-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: task-zookeeper:2181

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

volumes:
  mysql_data:

networks:
  task-network:
    driver: bridge